=== nadikakpathirana/xml-examples/with_xml_schema/studentSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="students">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="student" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="id" type="xs:integer"></xs:element>
              <xs:element name="name" type="xs:string"></xs:element>
              <xs:element name="age" type="xs:integer"></xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== nadikakpathirana/xml-examples/with_xml_schema/students.xml
<?xml version="1.0" encoding="UTF-8"?>
<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="studentSchema.xsd">
  <student>
    <id>001</id>
    <name>Nadika</name>
    <age>23</age>
  </student>
  <student>
    <id>002</id>
    <name>Koshala</name>
    <age>23</age>
  </student>
</students>
